### ISSUE TITLE
ETA for imv-3.0.0?

### ISSUE THREAD

**Issue by vvug** [eXeC64/imv#125]
Is there an approximate ETA for imv-3.0.0? Thanks.

**Comment by eXeC64** [comment]
I had been trying to get it out ~5 months ago, but due to a general dissatisfaction with the command parsing & syntax I held off on releasing 3.0. Then life started taking up all my free time.

To be honest, it's good enough for what it's needed for. I'll try and get it out either this weekend, or in the next couple of weeks.

**Comment by eXeC64** [comment]
v3 has been released
