### ISSUE TITLE
Copyright years are missing

### ISSUE THREAD

**Issue by paride** [eXeC64/imv#126]
A valid copyright notice should include the copyright years, see for example:

https://www.gov.uk/copyright

Please include them in the LICENSE file. Thanks!

**Comment by eXeC64** [comment]
Is it necessary?> You can mark your work with the copyright symbol (©), your name and the year of creation. Whether you mark the work or not doesn’t affect the level of protection you have.I always viewed the marks as a guide to anyone trying to identify the copyright holder. The date of authorship, or the last time it was touched doesn't determine copyright coverage. The only use I can see is dating work, but git covers that, as does the changelog.I'm reluctant to add a year, since it becomes something that needs to be kept up to date without providing additional value.

**Comment by paride** [comment]
In all the documents explaining how to properly write a copyright claim I've encountered it was always indicated to specify the copyright years. But IANAL.

I think the sentence you quoted refers to the fact that, in absence of a copyright notice, you're still protected by the copyright law with an "all rights reserved" default. Again, IANAL.

If you are going to leave the copyright years out feel free to close this issue. Please don't take me for a bureaucrat :)

**Comment by eXeC64** [comment]
I'm not a lawyer either, but I did a quick search around to double-check my hunch: Including copyright year is common practice, but does not affect coverage. In the US undated works from after 1978 are explicitly covered, and in the UK no date is required, as per your link.

I'm confident with the current protection, so I'll close this.
