### ISSUE TITLE
Allow multiple fonts for the overlay

### ISSUE THREAD

**Issue by chiraag-nataraj** [eXeC64/imv#143]
Specifying one font is great...if all of your text is in one language. Since my locale is `kn_IN.UTF8`, my directory names (at least the XDG ones, like Documents, Downloads, etc) are in Kannada. However, since things like commands are still in English, this creates a predicament where either my folder name shows up with question marks or I can't read the commands as I type them (or the _rest_ of the folder names, such as `/home/chiraag/`.

`urxvt` solves this with a fairly elegant solution where it starts with a base font and allows you to specify additional fonts it will look at to see if they can display the specified code block. This means that with enough fonts specified, things look fairly decent (putting aside that the terminal generally looks like shit with non-fixed-width fonts...)!

If I were able to specify multiple fonts for `overlay_font` in the config file, I would be able to work around this issue. I haven't yet looked at the codebase, but I am entirely willing to contribute in the form of testing and possibly coding (I don't entirely trust my C...).

**Comment by chiraag-nataraj** [comment]
I suspect [TTF_GlyphIsProvided](https://www.libsdl.org/projects/SDL_ttf/docs/SDL_ttf.html#SEC37) can be used to query whether a specific font provides a glyph, but I don't know how long each lookup takes (and there's got to be a better way to query this than for each individual character...).

**Comment by eXeC64** [comment]
Text is only redrawn when the image is changed, or resized, etc so I'm too worried about the cost of `TTF_GlyphIsProvided`, since it'll be run in a quick burst during a time the user expects the application to be busy, not continuously.

I think the multiple font solution with automatic fallback makes sense here. Being English, I'm a little ignorant of the specifics of your case so: While non-western fonts lack the latin alphabet, do they contain commonly used punctuation on computers: `[]()/+-` etc? That is, when displaying a path, would the font need to switch back and forth for the path separators '/`, or could the whole path just be rendered in your native font?

My first thought here was that I may have to reimplement `TTF_RenderUTF8_Blended` to handle multiple fonts, and have my own logic for positioning individual characters. However, I'm now thinking "spans" of characters might work. That is, loop through the characters, until a non-displayable one is found. Check if there's a font we can switch to that has it. If yes, render the text displayable so far, and start a new string with the new character and the new font. If no, continue with the current font.

The downside to that is splitting UTF-8 text makes me nervous, given the things non-western character sets can do.

**Comment by chiraag-nataraj** [comment]
> I think the multiple font solution with automatic fallback makes sense here. Being English, I'm a little ignorant of the specifics of your case so: While non-western fonts lack the latin alphabet, do they contain commonly used punctuation on computers: []()/+- etc? That is, when displaying a path, would the font need to switch back and forth for the path separators `/`, or could the whole path just be rendered in your native font?

The font I'm using (at the very least) seems to handle `/` and `[]` just fine, but the path contains a mix of characters (some latin, some Kannada), and there's no strong guarantee that the path itself will only be in one language (given the FHS and so on, it is virtually guaranteed that anyone running with a locale other than `en_*.UTF8` will have a path consisting of characters from disparate character sets.

**Comment by eXeC64** [comment]
Removing this from v3.1.0, which I'm hoping to release soon. At the moment I'm just getting a last couple of bug fixes in, this will have to go for v3.2.0

**Comment by eXeC64** [comment]
I'm doing a rather large refactor which uses cairo + pango for text rendering. Various texts from [this sample file](https://www.w3.org/2001/06/utf-8-test/UTF-8-demo.html) all render correctly now. This will be resolved once the refactor is in a tidy enough state to publish.

**Comment by eXeC64** [comment]
This is merged to master, and will be part of the v4 release.
