### ISSUE TITLE
Images load in strange order.

### ISSUE THREAD

**Issue by c-edw** [eXeC64/imv#146]
Both `find . | sort -V | imv -d` and `imv .` seem to load and display images in a strange order. I would expect it to load images in an order according to filenames, like feh does.

**Comment by Jeinzi** [comment]
That happens on my system, too. I didn't notice it before, as I always use something along the lines of `imv *.jpg`, which loads the images in the correct order.

**Comment by eXeC64** [comment]
Does the order of images output by `find . | sort -V ` not match the order of images when this is piped into `imv`?

I would expect imv to preserve the order of paths provided via stdin. As for `imv .`, images are loaded in the order returned by `readdir()`.

Do you still see the weird behaviour with `find . -type f`? My hunch is that imv is being passed directories, and loading those in `readdir()` order, with the individual images being loaded after.

**Comment by Jeinzi** [comment]
> Do you still see the weird behaviour with `find . -type f`?
No, for me that solves it, and also halves the number of images loaded.

**Comment by c-edw** [comment]
Yes, adding `-type f` resolves this problem for me, so I think your theory is correct.

**Comment by eXeC64** [comment]
Closing as works-as-designed in that case.

**Comment by c-edw** [comment]
I would like to make an appeal to you. `find . -type f | sort -V | imv -d` just isn't intuitive for viewing images in order. It is beautiful, but not intuitive. Would you consider simplifying this?

**Comment by eXeC64** [comment]
@c-edw I've been thinking about this a little bit. Essentially, a prerequisite to the gallery mode that's been on my todo list for years would be a complete overhaul of imv's internal file list infrastructure. Instead of just being a linked list of file names it could be a proper data structure that holds a little more metadata (file name, pointer to backend that can handle it, size, last-modified timestamp, pointer to thumbnail, etc.). This would have  the ability to sort and re-order files at runtime.

It's unlikely to appear in the next release though. I'm currently letting imv settle after the multi-backend refactor before putting out a new minor version.

Also, it's important to me that new features stay out of the way. Those who prefer a dumb image viewer shouldn't suffer bloat or new things getting in their way.

**Comment by Faalagorn** [comment]
I found that issue while searching for `--version-sort` equivalent of feh. While piping does work (for me `ls | sort -V | imv` does the job), is there any reason for preventing to add such switch? Not sure if I'd write PR myself, but shouldn't be too hard unless there are some reasons behind it
