### ISSUE TITLE
Setting keybindings as arguments

### ISSUE THREAD

**Issue by stammon** [eXeC64/imv#151]
One of the features feh has, is to pass shell commands as flags, to be executed when a key is pressed

    -A, --action [flag][[title]]action
             Specify a shell command as an action to perform on the image.  .....

    --action1 .. --action9 [flag][[title]]action
             Extra actions which can be set and triggered using the appropriate number key.

Usecases for that can be things like going through huge number of images, putting them into different collections. Imv has the p binding (which uses exec to echo the current image's name). That is useful and extensible, but not quite what I need. I want to have a default imv config for everyday usage and have a script passing different commandline options to imv.

My feature requests:
- Add a new bind command, which makes it possible to dynamically add keybindings as a command.
- Add a new commandline flag like `-c commandstring` that passes a string of commands, that should be executed, when starting after loading the default config.

This makes extending imv with scripts very flexible without changing the default config for a specific usecase. By my estimations it also shouln't need too many changes to the code. I'm curious about your opinion

**Comment by eXeC64** [comment]
I think a bind command is a reasonable addition. As for the `-c` flag, I think it might be less tedious (in terms of escaping+chaining commands) to allow the `-c` flag to be specified multiple times, each time appending a new command to run at startup.

Overall though, it seems to me that having a separate imv config for different workflows and invoking imv with the `imv_config` environment variable overriden would be a much tidier way of achieving the same thing. The biggest inconvenience is the lack of support for including a default config and overriding it.

Also, I'm leaning more and more towards the bind command overriding existing conflicting binds, rather than being blocked if an existing bind is contradictory/conflicting.

**Comment by eXeC64** [comment]
Master now contains a `bind` command, and a `-c` flag for specify commands to run at startup. Marking fixed.
