### ISSUE TITLE
Binary name clash with renameutils

### ISSUE THREAD

**Issue by paride** [eXeC64/imv#161]
Hello @eXeC64, I don't remember if I already bugged you about the following; if I did I apologize.

The `imv` binary name is already used by the [renameutils](https://www.nongnu.org/renameutils/) package, which has been around since 2001. This means that `imv` (the viewer) won't be able to be packaged as-is in all the distributions which have a "no clashes in installed binary files" policy and which also distribute renameutils. Debian an Ubuntu are among these.

I'm the Debian maintainer of `imv` and I had to rename the binary to `imvr` to avoid the name clash. This is of course unfortunate and annoying. Would you consider renaming the binary file this project installs? You could of course provide a fallback symlink (which I won't include in the Debian package).

Thank you!

**Comment by eXeC64** [comment]
Hi @paride,

When I first started imv, I did check for name clashes but either through incompetence or bad luck I missed renameutils. I've been thinking about this problem for a little while, and I'm reluctant to change the name.

The rename and symlink option doesn't appeal much, since it doesn't seem to solve anything. Your package ends up looking the same as it does now, and everyone else gets an extra bit of indirection.

As I've been working on the v4 release of imv, things have changed a little bit. imv no longer uses SDL2 to manage windows, instead shipping two binaries that handle Wayland and X11 natively: `imv-wayland` and `imv-x11`. To allow seamless usage to users, `/usr/bin/imv` itself is now provided as a [shell script](files/imv) that checks whether a Wayland compositor is available before running the appropriate build.

For Debian and other distributions with similar policies, this still has the same name-collision problem. However, I suggest for v4 you can either ditch the script, letting users run `imv-wayland` or `imv-x11` directly, or rename the script to something like `imv-run` or `imv-open`. Alternatively, you may wish to ship imv as two different packages, both providing an imv meta-package, but one is the Wayland implementation and the other is X11.

Hopefully, that's a little better than the `imvr` compromise. I'm going to close this issue, as I don't expect to be making any changes, but you're welcome to suggest alternate approaches or argue the point further, I'll listen.
