### ISSUE TITLE
background color works only works with secondary and primary colors

### ISSUE THREAD

**Issue by rien333** [eXeC64/imv#164]
Setting the background to more primary colors like `#ff0000` and `#ff00ff` works fine, but anything in between (e.g. `#2e3440`) shows a white background color. This happens both when the background is set from the   commandline, as well as when it's set from the config file. 

Git version, X11, arch linux. FYI, I have applied the `sed` fix discussed in https://github.com/eXeC64/imv/issues/163.

**Comment by rien333** [comment]
Given that the master branch of this project now is unstable, is it  even helpful to report bugs like these, or are they only a temporary artefact of your v4 development trajectory? For example, I've experienced enormous memory likes with the newest git build of imv.

**Comment by eXeC64** [comment]
Fixed by 324dbd7

The main reason I merged my in-progress v4 work to master was to get more eyeballs on it. Reporting these bugs is very helpful - since I don't use the background colour beyond black and chequerboard it's very unlikely I would have caught this prior to release. Memory leaks are something I've not yet looked at, but need to address as well.

All bug reports are welcome :)
