### ISSUE TITLE
4.0.0_rc1-1 release breaks scaling and viewing options on wayland

### ISSUE THREAD

**Issue by bunwayenterprises** [eXeC64/imv#177]
Just upgraded to **v4.0.0_rc1-1** from **v3.1.2** on arch with sway 1.2-rc2.

I currently have the following scaling option and binds set in my config file which no longer work after upgrading. However, upon downgrading to the prior version they function fine.

I cannot see any changes in **imv(5)** to reflect a new config file schema.

**NOTE**: The setting and unsetting of ```SDL_VIDEODRIVER=wayland``` makes no difference.

```
[options]
scaling_mode = shrink
...
...
[binds]
<Shift+8> = scaling_mode none                                                                        
/ = scaling_mode full

<Shift+j> = pan    0 -100   
<Shift+k> = pan    0  100   
<Shift+h> = pan  100    0
<Shift+l> = pan -100    0  

<Shift+.> = exec mogrify -rotate 90  "$imv_current_file"   
<Shift+,> = exec mogrify -rotate -90 "$imv_current_file" 
```

**Comment by DarkDefender** [comment]
`scaling_mode` got changed to simply `scaling`

**Comment by DarkDefender** [comment]
For the pan binds, to need to change to upper case letters, so:
`<Shift+J> = pan ...`

**Comment by eXeC64** [comment]
I've not yet written the changelog for v4, but in order to fix keyboard layout handling I had to make the bind system backwards incompatible. Hence the version jump from v3 to v4, rather than v3.2. Since imv's configuration was already backwards compatible I did also tweak some of the command names and syntax.

The following ought to be what you want
```
[options]
scaling_mode = shrink
...
...
[binds]
<Shift+asterisk> = scaling_mode none                                                                        
<slash> = scaling_mode full

<Shift+J> = pan    0 -100   
<Shift+K> = pan    0  100   
<Shift+H> = pan  100    0
<Shift+L> = pan -100    0  

# These two are based on my UK keyboard layout, and are probably different for you
<Shift+less> = exec mogrify -rotate 90  "$imv_current_file"   
<Shift+greater> = exec mogrify -rotate -90 "$imv_current_file" 
```

You can find the keynames with `xev` or `wev`. They're the same names as sway's config, but the syntax for combining keys is different.

**Comment by bunwayenterprises** [comment]
Perfect, thanks again :)
