### ISSUE TITLE
Key repeat doesn't seem to work (Press and hold)

### ISSUE THREAD

**Issue by DarkDefender** [eXeC64/imv#179]
It seems like all key binds now only trigger on the "key down" event. So if you hold the key down it will only execute the command once.

So if you want to navigate with the arrow keys or hjkl, you have to repeatedly press the keys as holding them down doesn't seem to work.

**Comment by eXeC64** [comment]
This is a known issue that I keep forgetting about. I've done some research and see what I'm doing wrong. I'll try and get this fixed in the next day or two.

Wayland clients have to handle key repeat themselves, so I'm currently determining the best way to handle this without using timerfds (which glfw, SDL, etc. rely on) as they are Linux-only.

**Comment by eXeC64** [comment]
Actually it was easier than expected. Fixed by 40a738b.
