### ISSUE TITLE
See past commands

### ISSUE THREAD

**Issue by mb720** [eXeC64/imv#191]
`imv` v4.0.0-rc1 on Arch Linux works great for me!

I'd like to scroll through past commands that I've entered.

For example, after I did something like

    :exec cp "$imv_current_file" ~/target.jpg

it would be great if I could press the up arrow key, ^p, or ^k to see that command again.

This way, I could alter the command and call it again.

**Comment by eXeC64** [comment]
Yes, this is something I'd like to have. It's a to-do feature. There's a lot of improvements to be made to the console in imv

**Comment by eXeC64** [comment]
Basic command history editing has been merged to master. It allows for readline-like editing, with up/down and ctrl+p/ctrl+n to go through the command history, as well as ctrl+a/e and let/right arrow keys to move around within the line. It also fixes backspace only deleting a single byte, rather than a whole UTF-8 character.
