### ISSUE TITLE
Next image on slow filesystems skips several images

### ISSUE THREAD

**Issue by farid-fari** [eXeC64/imv#201]
I mount remote filesystems using the `sshfs` -- from `imv`'s point of view, it's a filesystem like any other.

Then I open a directory using `imv .`. When I press the right arrow key to see the next image, it might take a second for the image to be retrieved through ssh (especially for large images/gifs), and when it does load, `imv` has skipped a few images already.

I'm using the wayland version 4.0.1, on Arch Linux and sway.

**Comment by eXeC64** [comment]
I've been suffering from this too actually, I've just not had time to look into it. I can reproduce this, so will work on a fix soon.

**Comment by flupe** [comment]
I've had the same issue for years, and finally decided to take a stab at it tonight.
My little investigation led me to understand that the culprit is the key timer and key listener in `wl_window.c`.
That is, when someone presses the key to go to the next image, and the latter is slow to load, somehow `wl_window.c` receives the "key released" event with some delay, so the key-repeat timer has had time to fire already. (For me, around 9 times or so).

Commenting [these lines](https://github.com/eXeC64/imv/blob/master/src/wl_window.c#L200-L214) disables key-repeat and the problem no longer happens. But of course we do want key repeat.

Now it's only a matter of findind why the "key released" event is delayed i.e why image loading interferes with retrieving keyboard events from wayland or whatever.
Sadly I would love some pointers as my understanding of C and wayland libraries is quite limited.

**Comment by flupe** [comment]
Ok, seems adding `wl_display_roundtrip(window->wl_display);` before [these lines](https://github.com/eXeC64/imv/blob/master/src/wl_window.c#L200-L214) (inside the `if`, at the top) does the job, i have no issues with skipped images so far.

Pretty much the same fix was used for #305 , but perhaps in this case it would be best to add this line inside the timer callback than the main keyboard key handler.
