### ISSUE TITLE
Donations

### ISSUE THREAD

**Issue by mb720** [eXeC64/imv#226]
Hi!

I'd like to support this project with some donations.

Is there a way to do that?

**Comment by eXeC64** [comment]
Hi, that's very kind of you.

Due to my full time job, my financial needs are well met. What I often lack for is time. However, if you're keen to support open source development on Linux, a friend of mine, Drew DeVault, works on open source software full time, funded primarily by donations. He's the author of [sway](https://github.com/swaywm/sway), [wlroots](https://github.com/swaywm/wlroots), a [compelling github alternative](https://sourcehut.org/), and many other less glamorous but important projects.

I'd like to encourage you to pass on to Drew any donation you intended to make to imv's development, to allow him to continue working on similar open source projects full time.

Some related links:
* [Drew's donations page](https://drewdevault.com/backers)
* [Drew's GitHub repositories](https://github.com/ddevault)
* [Drew's SourceHut repositories](https://git.sr.ht/~sircmpwn)

Thanks!
