### ISSUE TITLE
imv fails with FreeImage_Load returned NULL

### ISSUE THREAD

**Issue by MatthiasCoppens** [eXeC64/imv#299]
`imv v4.1.0-33-g489421b-dirty`
`sway version 1.5-32b93ef6 (Dec  1 2020, branch 'HEAD')`
Tested with `freeimage` version 3.18.0-r1 and 3.18.0-r2 from the Gentoo repo.

**Comment by ionenwks** [comment]
I've seen a warning about implicit declaration of strdup() with librsvg disabled, I'm assuming rsvg.h was the only thing providing string.h. Adding the header to backend_freeimage.c seems to fix this.

Looked into this because going to attempt to become the maintainer of imv in Gentoo soon and do a version bump with a quick fix for this (along other ebuild fixes).

**Comment by MatthiasCoppens** [comment]
Can confirm this fixes it on my system

**Comment by MatthiasCoppens** [comment]
(tested with media-gfx/imv-4.1.0-r1)
