### ISSUE TITLE
Uncontrollable flickering in Wayland viewing any file

### ISSUE THREAD

**Issue by tjkopena** [eXeC64/imv#305]
Following a recent update, imv started flickering uncontrollably all the time. It seems to be continually switching between an upscaled image and the original image. This short clip shows the behavior:

https://user-images.githubusercontent.com/1175848/103292574-18948d00-49bc-11eb-8404-79b4c7733b5f.mp4

imv loads the image and is immediately flickering. I then scale the image up and then down but it continues flickering throughout. Note that imv does continue being responsive, i.e., all keyboard commands continue functioning and it exits cleanly.

Environment is Arch Linux using Wayland (sway) on a Lenovo Thinkpad. I see the same behavior from both imv v4.1.0 currently packaged in the AUR as well as imv-wayland v4.2.0 built from git a4bb341. The imv config file in ~/.config/imv/config has only comments. Image file or type doesn't matter, this happens with a wide variety of PNGs and JPGs. Listing multiple files or only one file on the command line doesn't make a difference, and neither does switching between them.

**Comment by eXeC64** [comment]
This is strange, as I do my development on Arch, with sway on a Lenovo thinkpad and have never encountered this. I just installed the imv package from the Arch repos and it works fine for me. Can you be more detailed about which versions of Arch packages you have?

For me:

- imv 4.2.0-2
- sway 1:1.5.1-1
- freeimage 3.18.0-7
- linux 5.9.14.arch1-1

I'd also ask you to try running `imv-wayland image.png` instead of `imv image.png` to check that `/usr/bin/imv` isn't launching the X11 version inadvertantly for you.

Lastly, in that video it looks like imv is started floating rather than tiled. Can you share any custom configuration you have for how sway arranges the imv window?

**Comment by tjkopena** [comment]
It's definitely related to floating. I had forgotten until you mentioned it that I have imv configured to open floating, that's not imv's standard behavior. It's done via this in my sway config:

`for_window [app_id="imv"] floating enable`

If I comment that out, imv opens in a tiled window correctly and shows no issue. Curiously, if I switch the tiled window to floating mode there is no issue, I get the expected stable behavior. So the problem seems related to _starting_ in floating mode, as opposed to just being in floating mode. Starting in fullscreen mode via a similar sway config presents no problem.


For reference, my packages are at:
* imv 4.1.0-2
* sway 1:1.5.1-1
* freeimage 3.18.0-7
* linux 5.9.8.arch1-1

But again note that it also happens w/ imv 4.2.0 from git.

Using `imv-wayland` explicitly doesn't change the behavior.

**Comment by ephase** [comment]
Hi,

I've got the same problem here, but when I disable my scale factor on sway config, imv work properly.

**Comment by eXeC64** [comment]
Thanks @ephase - scaling was the key for me to reproduce this locally.
