### ISSUE TITLE
Ability to display just file name, not whole path

### ISSUE THREAD

**Issue by Faalagorn** [eXeC64/imv#312]
Currently `$imv_current_file` variable prints the whole file path, but I'd like it to show just the file name. I tried searching but couldn't find a way to do it with the current implementation, but maybe a new variable could be added for it?

**Comment by rifazn** [comment]
I think you are better off using native bash features like globs (`*`) and parameter substitution for this.

In your case, the following should return just the filename from the `$imv_current_file` variable:

    echo ${imv_current_file##*/}

Explanation:

The above command is in the format: `${var##pattern}`. 

`##` tells bash to start removing every character from the _beginning_ of `$var` that satisfies the pattern `*/`.

Using `%%` instead of `##` will match and remove characters (that match the pattern) from the _end_ of the variable. 

Or, you can just use the `basename` program to have the same effect. I think some distributions have it pre-installed.

So executing

```
basename "$imv_current_file"
```

Should echo just the file name.

**Comment by Faalagorn** [comment]
> ```
> basename "$imv_current_file"
> ```
Thanks! I noticed in manual that there's an option for using bash commands, but I couldn't figure it out. I indeed have basename installed so using `$(basename "$imv_current_file")` seemed to help in my case, thank you very much for a clue! :)
