### ISSUE TITLE
urls to gifs and other formats

### ISSUE THREAD

**Issue by japrogramer** [eXeC64/imv#58]
it would be great if this app could be passed in a file or comma seperated list of urls.
and than use curl to download one at a time while being displayed, and once transitioning to the next gif
delete the previous file from /tmp. or even keep file, in a predefine directory if user presses a key to trigger the action.

**Comment by czarkoff** [comment]
Actually, the main advantage of this program is its filtering capability, which allows to use it in scripts. Eg. one can use a script like this:
```
#!/bin/sh

IMGDIR="`mktemp -dt imv.XXXXXX`"

for url in "$@"
do
	filename="`echo \"$url\" | sed -E 's,^(.*/)*([^/]+)$,\2,'`"
	curl -so "$IMGDIR/$filename" "$url" && echo "$IMGDIR/$filename"
done | imv - | sort | uniq | xargs rm

[ "`ls $IMGDIR`" == "" ] && exec rm -R $IMGDIR

echo "${PS1}ls \"$IMGDIR\""
ls "$IMGDIR"
```
This script won't load and display files in parallel because `imv` starts displaying images only after all of the standard input is read. And this is actually something I'd love to see changed, so that `imv` would hurry to display a file as soon as it learns about it.

**Comment by eXeC64** [comment]
A script like the one above would be the preferred solution.

Letting imv start viewing input files before the input is terminated sounds like it could be quite useful, but would require some thought regarding edge cases. 

Viewing a single image without a script will soon be supported too by piping data in with a flag (probably `-x`): `curl http://example.com/image.jpg | imv -x`
The work on that's not finished yet though.
