### ISSUE TITLE
imv only works on Linux

### ISSUE THREAD

**Issue by eXeC64** [eXeC64/imv#67]
A point @czarkoff raised is that imv currently uses `inotify` to watch files. We should either use a portable interface, or provide platform dependent sourced files for the reload subsystem. That is, keep `reload.h` the same, but rename `reload.c` to `reload_inotify.c` and provide `realod_kqueue.c` or similar as an alternative. Then whichever implementation is available on the current platform can be used at build-time.

**Comment by jdiez17** [comment]
Platform-specific implementations of the reload API sound good to me.
Another option would be to replace `reload.{c,h}` with a library that
provides the functionality on all platforms.

**Comment by eXeC64** [comment]
My preference would be to avoid adding new libraries when possible, to try and keep the requirements of imv small. Compatibility with other unices and unix-likes is definitely something I'd like to maintain support for.

**Comment by czarkoff** [comment]
I see three possible ways to provide this functionality on non-Linux platforms:
* [`kqueue(2)`](http://www.openbsd.org/cgi-bin/man.cgi/OpenBSD-current/man2/EV_SET.2?query=kqueue) is available on BSDs (including OS X and probably Minix).
* [`libinotify-kqueue`](https://github.com/dmatveev/libinotify-kqueue) adds inotify support to kqueue-enabled systems.
* [`stat(2)`](http://pubs.opengroup.org/onlinepubs/9699919799/functions/stat.html) is available on every Unix-like system.

My initial urge was to do exactly as @eXeC64 says: move `reload.c` to `reload-inotify.c`, add `reload-kqueue.c` and some magic to Makefile to pick right thing. There are dragons here, as kqueue requires keeping descriptors for all watched files around, which has potential to cause descriptor starvation. Also, kqueue won't work on some filesystems. Same issues apply to libinotify-kqueue.

I'd rather go with the following option:
* Call `stat(2)` and remember mtime when adding files to navigator.
* Call `stat(2)` again before displaying file and compare actual mtime to stored mtime.

This should not have significant overhead. In fact it may turn out to be faster then creating and destroying inotify watches (one `stat(2)` operation instead of one `write(2)` and two `read(2)`s), and it is more reliable in some scenarios. Eg. inotify will not report changes on NFS.

If this plan sounds sane, I'll come up with pull request.

**Comment by czarkoff** [comment]
P.S.: while testing my approach I've noticed that libinotify-kqueue doesn't seem to work for me at all...

**Comment by eXeC64** [comment]
Fixed by #68
